version: 0.0
os: linux
files:
  - source: /CreateFile.java
    destination: /home/ec2-user/
hooks:
  Install:
    - location: scripts/compile_java
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/run_java
      timeout: 300
      runas: ec2-user
