version: 0.0
os: linux
files:
  - source: /HelloWorld.java
    destination: /home/ec2-user/
hooks:
  AfterInstall:
    - location: scripts/compile_java
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/run_java
      timeout: 300
      runas: root
